### ISSUE TITLE
Build failing with fmt 12

### ISSUE THREAD

**Issue by tramtrist** [Alexays/Waybar#4496]
Have been trying to build Waybar in Slackware -current and have not been able to.  fmt12 is installed.  Not using any special options or flags.  Any ideas? 🙏
```
In file included from /usr/include/fmt/ostream.h:23,
                 from ../include/util/json.hpp:3,
                 from ../include/modules/hyprland/backend.hpp:10,
                 from ../include/modules/hyprland/workspaces.hpp:16,
                 from ../src/modules/hyprland/workspace.cpp:8:
/usr/include/fmt/chrono.h: In member function ‘decltype (ctx.out()) fmt::v11::formatter<tm, Char>::do_format(const tm&, FormatContext&, const Duration*) const’:
/usr/include/fmt/chrono.h:2144:55: error: there are no arguments to ‘locale_ref’ that depend on a template parameter, so a declaration of ‘locale_ref’ must be available [-Wtemplate-body]
 2144 |     auto loc_ref = specs.localized() ? ctx.locale() : locale_ref();
      |                                                       ^~~~~~~~~~
/usr/include/fmt/chrono.h:2144:55: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
[157/176] Compiling C++ object waybar.p/src_modules_sni_host.cpp.o
[158/176] Compiling C++ object waybar.p/src_modules_sni_tray.cpp.o
[159/176] Compiling C++ object waybar.p/src_modules_keyboard_state.cpp.o
[160/176] Compiling C++ object waybar.p/src_modules_sni_item.cpp.o
[161/176] Compiling C++ object waybar.p/src_modules_clock.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by tramtrist** [comment]
I  was able to compile using fmt 11.1.4
