### ISSUE TITLE
Clock does not recognise fmt-10.0.0 format specifier

### ISSUE THREAD

**Issue by bradrn** [Alexays/Waybar#2363]
Version 10.0.0 of [fmt](https://fmt.dev/latest/index.html) introduced support for padding seconds, minutes and hours (so e.g. producing output like ` 1` rather than `01`). I have tested that this works on my system by testing the following C++ program:

```cpp
#include <fmt/chrono.h>

int main() {
    auto t = tm();
    t.tm_year = 2010 - 1900;
    t.tm_mon = 7;
    t.tm_mday = 4;
    t.tm_hour = 1;
    t.tm_min = 15;
    t.tm_sec = 58;
    fmt::print("{:%_I}", t);
    return 0;
}
```

As expected, this prints ` 1` (with an initial space).

However, when I try using the same format string with waybar, it simply produces the literal text `%_I`:

![image](https://github.com/Alexays/Waybar/assets/17613703/fe61ebd3-c334-4194-ad13-80c6badfdc6b)

My `clock` configuration is as follows:

```
    "clock": {
        "tooltip-format": "<tt>{calendar}</tt>",
        "format": "{:%_I}",
        "calendar": {
            "mode": "month",
            "on-scroll": 1,
            "weeks-pos": "left",
            "format": {
                // omitted for brevity
            }
        },
        "actions":  {
                // omitted for brevity
        }
    },
```

Note that the format string is exactly the same as that used in the C++ program above.

For reference, I am using EndeavourOS (so basically Arch Linux), with `waybar-0.9.20-2` and `fmt-10.0.0-1`. My compositor is Sway, though I presume that makes no difference.

**Comment by LukashonakV** [comment]
Hi @bradrn , As far as I know, the waybar now doesn't support fmt 10 version. But I might be wrong. Anyway I'll check it, once have a time. Thank you

**Comment by bradrn** [comment]
> waybar now doesn't support fmt 10 version

Insofar as I’m aware, it shouldn’t matter, since the call to `fmt::print` (or whichever function is used by `waybar`) should be the same either way. It certainly works on my machine with fmt-10.0.0 — it’s just that the new format specifiers introduced by that version don’t seem to work.

**Comment by LukashonakV** [comment]
> > waybar now doesn't support fmt 10 version
> 
> Insofar as I’m aware, it shouldn’t matter, since the call to `fmt::print` (or whichever function is used by `waybar`) should be the same either way. It certainly works on my machine with fmt-10.0.0 — it’s just that the new format specifiers introduced by that version don’t seem to work.

Clock module uses the exact fmt library. So.. it's definitely a strange case when you are able to use fmt10 ... but clock component shows unexpected results.. .OK, let me check...

**Comment by bradrn** [comment]
I probably should have mentioned that other format strings show the expected results, e.g.:

![image](https://github.com/Alexays/Waybar/assets/17613703/aca04110-7c68-4c08-b3a2-bfd0ae69c30a)

This is with `{:%a %Od %b,\t%I:%M %p}`.

**Comment by osmak1234** [comment]
I'm currently experiencing issues with waybar on arch.
Initially after system update, waybar stopped working, because of a missing library fmt9, I had fmt10.
I build fmt9 from [source](https://fmt.dev/9.0.0/) and the problem was I was missing fmt10. I installed both at the same time, I'm stuck on this error message and waybar build crashing on be from the clock test module. 

after install from AUR:
`waybar: symbol lookup error: waybar: undefined symbol: _ZN6spdlog7details7log_msgC1ENS_10source_locEN3fmt2v917basic_string_viewIcEENS_5level10level_enumES6_ `

When trying to build:
`/usr/bin/ld: clock.cpp:(.text+0x3881): undefined reference to `fmt::v9::detail::assert_fail(char const*, int, char const*)'`
there is like 1000 of these, each containing fmt::v9, but when I have only it installed it errors the same.

Sorry if this is cryptic/incomplete, I'm not that familiar with cpp or it's debugging.

**Comment by DigitalDragon64** [comment]
Probably related to this: Since my last system update (waybar and fmt were both updated) the decimal points are printed, when just giving the format specifier `%S`.

**Comment by ti-mo** [comment]
@DigitalDragon64 Same, created an issue for it here: https://github.com/Alexays/Waybar/issues/2378.

**Comment by LukashonakV** [comment]
Hi @bradrn , I found your conversation fmtlib/fmt#3516
Finally I built waybar with dependency fmt = 10.0.0. There issue here: [test/chrono-test.cc](https://github.com/fmtlib/fmt/pull/3271/files#diff-1ee69b67ff4425f4dfb5595c0eee868c39579a3ad8cdc48d51817c4ffc4b5179R956)
format: 
`EXPECT_EQ(fmt::format("{:%_OI,%_OH,%_OM,%_OS}", tm), " 1, 1, 2, 3");`
`EXPECT_EQ(fmt::format("{:%-OI,%-OH,%-OM,%-OS}", tm), "1,1,2,3");`
doesn't work. In the same time I see that both merge requets were approved and now are part of the vmt:10 version according release note. See [fmt 10 RN](https://github.com/fmtlib/fmt/releases/tag/10.0.0) - row `Improved validation of format specifiers for std::chrono::duration (https://github.com/fmtlib/fmt/issues/3219, https://github.com/fmtlib/fmt/pull/3232). Thanks [@ShawnZhong (Shawn Zhong)](https://github.com/ShawnZhong).`
So actually looks like need to raise an issue to fmt upstream.

**Comment by bradrn** [comment]
> So it actually looks like it needs an issue to be raised to fmt upstream.

Except that exactly the same format string works when I directly use my version of `fmt` (see the test program above), but doesn’t work when I use it with `waybar`. So this can’t be an issue with `fmt`.

**Comment by LukashonakV** [comment]
@bradrn, Waybar uses date features like date::zoned_time. According cpp reference now it included into C++20 standard. I've just checked: fmt doesn't work with date::zoned_time. In the same time pure sys_time timpoint works well with fmt.
I'll create an issue to fmt to extend glibc extension on the whole chrono library including TZ API.

**Comment by bradrn** [comment]
Ah, that makes sense! Thanks for looking into this @LukashonakV.

**Comment by Alexays** [comment]
Closing as an upstream fmt limitation. As @LukashonakV tracked down, the new fmt-10 padding specifiers (`%_I`, `%-OS`, etc.) work on a plain `sys_time`/`tm` but are silently dropped for `date::zoned_time`, which is exactly what the clock module formats — hence why your standalone test printed ` 1` but Waybar rendered the literal `%_I`. That's the fmt issue raised upstream at fmtlib/fmt#3572, not something Waybar can fix on its side. Thanks for the clear repro 🙏 If fmt extends these extensions to the chrono TZ API, we'll happily revisit — feel free to reopen then.
