### ISSUE TITLE
Build failed after 0c1f1f2

### ISSUE THREAD

**Issue by Billli11** [Alexays/Waybar#4215]
Build failed after 0c1f1f2 (#3544). revert it fix building.

gcc version: gcc (GCC) 15.1.1 20250425

build output https://gist.github.com/Billli11/5eeaa2d268e08ac39f3c51e2389a3fdc

error

```
../src/modules/hyprland/windowcount.cpp: In constructor ‘waybar::modules::hyprland::WindowCount::WindowCount(const std::string&, const waybar::Bar&, const Json::Value&)’:
../src/modules/hyprland/windowcount.cpp:22:8: error: ‘gIPC’ was not declared in this scope; did you mean ‘IPC’?
   22 |   if (!gIPC) {
      |        ^~~~
      |        IPC
../src/modules/hyprland/windowcount.cpp:31:3: error: ‘gIPC’ was not declared in this scope; did you mean ‘IPC’?
   31 |   gIPC->registerForIPC("fullscreen", this);
      |   ^~~~
      |   IPC
../src/modules/hyprland/windowcount.cpp: In destructor ‘virtual waybar::modules::hyprland::WindowCount::~WindowCount()’:
../src/modules/hyprland/windowcount.cpp:40:3: error: ‘gIPC’ was not declared in this scope; did you mean ‘IPC’?
   40 |   gIPC->unregisterForIPC(this);
      |   ^~~~
      |   IPC
../src/modules/hyprland/windowcount.cpp: In static member function ‘static waybar::modules::hyprland::WindowCount::Workspace waybar::modules::hyprland::WindowCount::getActiveWorkspace()’:
../src/modules/hyprland/windowcount.cpp:73:26: error: ‘gIPC’ was not declared in this scope; did you mean ‘IPC’?
   73 |   const auto workspace = gIPC->getSocket1JsonReply("activeworkspace");
      |                          ^~~~
      |                          IPC
../src/modules/hyprland/windowcount.cpp: In static member function ‘static waybar::modules::hyprland::WindowCount::Workspace waybar::modules::hyprland::WindowCount::getActiveWorkspace(const std::string&)’:
../src/modules/hyprland/windowcount.cpp:83:25: error: ‘gIPC’ was not declared in this scope; did you mean ‘IPC’?
   83 |   const auto monitors = gIPC->getSocket1JsonReply("monitors");
      |                         ^~~~
      |                         IPC
ninja: build stopped: subcommand failed.
```

**Comment by Billli11** [comment]
Fixed in #4219
