### ISSUE TITLE
Can't compile with FMT 8.1.0

### ISSUE THREAD

**Issue by AngryPenguinPL** [Alexays/Waybar#1368]
When compiling Waybar 0.9.8 with newly updated fmt 8.1.0 I see this error:

```
../src/modules/clock.cpp:200:20: error: 'specs' is a private member of 'fmt::formatter<tm>'
DEBUG util.py:636:          auto& tm_format = specs;
DEBUG util.py:636:                            ^
DEBUG util.py:636:  /usr/include/fmt/core.h:715:64: note: in instantiation of function template specialization 'fmt::formatter<waybar::modules::waybar_time>::format<fmt::basic_format_context<fmt::appender, char>>' requested here
DEBUG util.py:636:      -> decltype(typename Context::template formatter_type<T>().format(
```

Full build log with more details is here: https://file-store.openmandriva.org/api/v1/file_stores/597775db70004e7530f2b3f4935fe56c68cd7fa4.log?show=true

Info: 
Waybar 0.9.8
FMT 8.1.0
OS: OpenMandriva Cooker x86_64
Compiler: LLVM/Clang 13.0.0
Linker: LLD

**Comment by ahmadraniri1994** [comment]
Same here, rebuild fmt and still can't compile.

**Comment by mazunki** [comment]
I hadn't seen this issue before posting mine. Here's a hotfix: 

https://github.com/Alexays/Waybar/issues/1379#issuecomment-1007846629.

**Comment by ahmadraniri1994** [comment]
> I hadn't seen this issue before posting mine. Here's a hotfix:
> 
> [#1379 (comment)](https://github.com/Alexays/Waybar/issues/1379#issuecomment-1007846629).

Dunno why, I tried your fork but my compilation  still complains about fmt.
